version: "3.7"
services:
  tile-changer:
    build: .
    image: jdayllon/tile-changer:lastest
    deploy:
      replicas: 1
    ports:
      - "8080:80"
    env_file:
    - .env
  mapea:
    build: mapea
    image: jdayllon/mapea:5.0.1
    deploy:
      replicas: 1
    ports:
      - "9080:8080"