apiVersion: v1
kind: PersistentVolume
metadata:
  name: tile-changer-pv-volume
  labels:
    app: tile-changer
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 128Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "./www/"